# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\"6\n\x07Inquiry\x12\r\n\x05nodes\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x02(\x05\x12\x0e\n\x06\x66\x61nout\x18\x03 \x02(\x05\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x02(\t2-\n\tInference\x12 \n\tInference\x12\x08.Inquiry\x1a\x07.Result\"\x00')

_INQUIRY = DESCRIPTOR.message_types_by_name['Inquiry']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Inquiry = _reflection.GeneratedProtocolMessageType('Inquiry', (_message.Message,), {
    'DESCRIPTOR': _INQUIRY,
    '__module__': 'inference_pb2'
    # @@protoc_insertion_point(class_scope:Inquiry)
})
_sym_db.RegisterMessage(Inquiry)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR': _RESULT,
    '__module__': 'inference_pb2'
    # @@protoc_insertion_point(class_scope:Result)
})
_sym_db.RegisterMessage(Result)

_INFERENCE = DESCRIPTOR.services_by_name['Inference']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _INQUIRY._serialized_start = 19
    _INQUIRY._serialized_end = 73
    _RESULT._serialized_start = 75
    _RESULT._serialized_end = 96
    _INFERENCE._serialized_start = 98
    _INFERENCE._serialized_end = 143
# @@protoc_insertion_point(module_scope)
